### ISSUE TITLE
macOS and difference between miryoku QMK and ZMK

### ISSUE THREAD

**Issue by xbladesub** [manna-harbour/miryoku#144]
I was using QMK for a while and after I built my 2nd board with nice-nanos I realized that Miryoku ZMK doesn't seems to work the same as miryouku qmk - for example I can't move my mouse pointer with zmk (there is no such issues  with qmk). Also karabiner keybindings doesn't work with miryoku zmk (everything is ok with qmk). 

All settings just default (only vi mode). Am I doing something wrong? I think miryouku zmk/qmk should have same behavior with same workflow settings?

**Comment by xbladesub** [comment]
Cannot use mouse-pr branch because of merge conflict 

![Screen Shot 2022-09-23 at 11 17 40 PM](https://user-images.githubusercontent.com/45129790/191995197-0d9a9b3e-b03b-4522-8bce-72b4c97ff09a.png)

**Comment by manna-harbour** [comment]
Issues are not being used for support. Please use the Discussions as described at https://github.com/manna-harbour/miryoku#discussions-and-support.
