### ISSUE TITLE
MIRYOKU_LAYOUT=vi Does Not Work

### ISSUE THREAD

**Issue by raviolispy** [manna-harbour/miryoku#194]
### Discussed in https://github.com/manna-harbour/miryoku/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **raviolispy** February 24, 2023</sup>
Using the below command, I can successfully compile for my iris rev7 (although curiously, I had to remove some things from the default version so the hex file was small enough). The other options I specified such as the QWERTY layout all work but the MIRYOKU_NAV=vi doesn't appear to shift the navigation keys to hjkl. Can anyone help please?

`qmk compile -c -kb keebio/iris/rev7 -km manna-harbour_miryoku  -e MIRYOKU_ALPHAS=QWERTY  -e MIRYOKU_CLIPBOARD=WIN  -e MIRYOKU_TAP=QWERTY -e MIRYOKU_NAV=vi`</div>

**Comment by manna-harbour** [comment]
Issues are not being used for support. Please use the Discussions as described at https://github.com/manna-harbour/miryoku#discussions-and-support. Issues will be created from or linked to Discussions as needed, after the Issue has been clarified in the Discussion.
