### ISSUE TITLE
Can this layout be made available on ZMK?

### ISSUE THREAD

**Issue by harshitgoel96** [manna-harbour/miryoku#3]
Can this layout be made available on ZMK?

**Comment by Percentnineteen** [comment]
I'm setting up a Corne on ZMK and was wondering if I could use your dev version as a starting point for my keycap. I was also wondering if you planned to work in bluetooth controls for ZMK given its focus on wireless functionality. Thanks.

**Comment by manna-harbour** [comment]
> I'm setting up a Corne on ZMK and was wondering if I could use your dev version as a starting point for my keycap. I was also wondering if you planned to work in bluetooth controls for ZMK given its focus on wireless functionality. Thanks.

Sure.  Please contact me privately to arrange this.  https://github.com/manna-harbour/manna-harbour/tree/main/contact

Bluetooth controls are on the media layer for the time being.
